#!/usr/bin/env bash

if [[ -s "/home/kostia/.rvm/environments/ruby-1.8.7-p371@rails2tutorial" ]]
then
  source "/home/kostia/.rvm/environments/ruby-1.8.7-p371@rails2tutorial"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/kostia/.rvm/environments/ruby-1.8.7-p371@rails2tutorial'" >&2
  exit 1
fi
