#!/usr/bin/env bash

if [[ -s "/home/kostia/.rvm/environments/ruby-1.9.3-p286@global" ]]
then
  source "/home/kostia/.rvm/environments/ruby-1.9.3-p286@global"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/kostia/.rvm/environments/ruby-1.9.3-p286@global'" >&2
  exit 1
fi
