# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1351323819);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1351323819);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1351354774);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1351351054);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 614400);
user_pref("browser.migration.version", 6);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20121025210744");
user_pref("browser.startup.homepage_override.mstone", "16.0.2");
user_pref("browser.syncPromoViewsLeft", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 13);
user_pref("extensions.enabledAddons", "langpack-en-ZA@firefox.mozilla.org:16.0.2,langpack-en-GB@firefox.mozilla.org:16.0.2,langpack-ru@firefox.mozilla.org:16.0.2,globalmenu@ubuntu.com:3.5.4,ubufox@ubuntu.com:2.1.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:16.0.2");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1351329213000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1351204973000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1351204973000},\"langpack-ru@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-ru@firefox.mozilla.org.xpi\",\"mtime\":1351204980000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1351329077000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1351329079000}}}]");
user_pref("extensions.lastAppVersion", "16.0.2");
user_pref("extensions.lastPlatformVersion", "16.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/locale");
user_pref("extensions.ui.locale.hidden", false);
user_pref("idle.lastDailyNotification", 1351328738);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-5, ISO-8859-1, windows-1251, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1351328738);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_viewing_mixed", false);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1351328738);
user_pref("toolkit.startup.last_success", 1351356282);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1353915703);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
