#!/usr/bin/env bash

if [[ -s "/home/kostia/.rvm/environments/ruby-1.9.2-p320@rails3tutorial" ]]
then
  source "/home/kostia/.rvm/environments/ruby-1.9.2-p320@rails3tutorial"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/kostia/.rvm/environments/ruby-1.9.2-p320@rails3tutorial'" >&2
  exit 1
fi
