#!/usr/bin/env bash

if [[ -s "/home/kostia/.rvm/environments/ruby-1.8.7-p302@global" ]]
then
  source "/home/kostia/.rvm/environments/ruby-1.8.7-p302@global"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/kostia/.rvm/environments/ruby-1.8.7-p302@global'" >&2
  exit 1
fi
