#!/usr/bin/env bash

if [[ -s "/home/kostia/.rvm/environments/ruby-1.8.7-p371@global" ]]
then
  source "/home/kostia/.rvm/environments/ruby-1.8.7-p371@global"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/kostia/.rvm/environments/ruby-1.8.7-p371@global'" >&2
  exit 1
fi
