#!/usr/bin/env bash

if [[ -s "/home/kostia/.rvm/environments/ruby-1.8.7-p302" ]]
then
  source "/home/kostia/.rvm/environments/ruby-1.8.7-p302"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/kostia/.rvm/environments/ruby-1.8.7-p302'" >&2
  exit 1
fi
